#pragma once

#include "./compiler.h"


#if defined(NGS_COMPILER_IS_MSVC) && defined(_MSVC_LANG) && _MSVC_LANG > __cplusplus
#	define NGS_CPP_VERSION _MSVC_LANG
#else
#	define NGS_CPP_VERSION __cplusplus
#endif

#define NGS_CPP_STANDARD_VERSION_26 202600L
#define NGS_CPP_STANDARD_VERSION_23 202302L
#define NGS_CPP_STANDARD_VERSION_20 202002L
#define NGS_CPP_STANDARD_VERSION_17 201703L
#define NGS_CPP_STANDARD_VERSION_14 201402L
#define NGS_CPP_STANDARD_VERSION_11 201103L
#define NGS_CPP_STANDARD_VERSION_03 199711L
#define NGS_CPP_STANDARD_VERSION_98 199711L

#if NGS_CPP_VERSION > NGS_CPP_STANDARD_VERSION_23
#	define NGS_CPP_STANDARD_HAS_26 1
#endif
#if NGS_CPP_VERSION > NGS_CPP_STANDARD_VERSION_20
#	define NGS_CPP_STANDARD_HAS_23 1
#endif
#if NGS_CPP_VERSION > NGS_CPP_STANDARD_VERSION_17
#	define NGS_CPP_STANDARD_HAS_20 1
#endif
#if NGS_CPP_VERSION > NGS_CPP_STANDARD_VERSION_14
#	define NGS_CPP_STANDARD_HAS_17 1
#endif
#if NGS_CPP_VERSION > NGS_CPP_STANDARD_VERSION_11
#	define NGS_CPP_STANDARD_HAS_14 1
#endif
#if NGS_CPP_VERSION > NGS_CPP_STANDARD_VERSION_03
#	define NGS_CPP_STANDARD_HAS_11 1
#endif
#if NGS_CPP_VERSION > NGS_CPP_STANDARD_VERSION_98
#	define NGS_CPP_STANDARD_HAS_03 1
#endif
#if 1
#	define NGS_CPP_STANDARD_HAS_98 1
#endif

#ifdef NGS_CPP_STANDARD_HAS_23
#	define NGS_CPP_STANDARD_IS_23 1
#elif NGS_CPP_STANDARD_HAS_20
#	define NGS_CPP_STANDARD_IS_20 1
#elif NGS_CPP_STANDARD_HAS_17
#	define NGS_CPP_STANDARD_IS_17 1
#elif NGS_CPP_STANDARD_HAS_14
#	define NGS_CPP_STANDARD_IS_14 1
#elif NGS_CPP_STANDARD_HAS_11
#	define NGS_CPP_STANDARD_IS_11 1
#elif NGS_CPP_STANDARD_HAS_03
#	define NGS_CPP_STANDARD_IS_03 1
#endif