#pragma once

#include "../defined.h"

#define NGS_MATH_LA_MATRIX_INTERFACE_BEGIN NGS_MATH_LA_INTERFACE_BEGIN namespace matrixes {
#define NGS_MATH_LA_MATRIX_INTERFACE_END } NGS_MATH_LA_INTERFACE_END
#define NGS_MATH_LA_MATRIX_ADAPTER_BEGIN NGS_MATH_LA_ADAPTER_BEGIN namespace matrixes {
#define NGS_MATH_LA_MATRIX_ADAPTER_END } NGS_MATH_LA_ADAPTER_END
#define NGS_MATH_LA_MATRIX_TRAIT_BEGIN NGS_MATH_LA_TRAIT_BEGIN namespace matrixes {
#define NGS_MATH_LA_MATRIX_TRAIT_END } NGS_MATH_LA_TRAIT_END