#pragma once

#if (not defined(NGS_MATH_SCALAR_DISABLE_EXPLICIT) && not defined(NGS_MATH_SCALAR_ENABLE_EXPLICIT)) || (defined(NGS_MATH_SCALAR_DISABLE_EXPLICIT) && defined(NGS_MATH_SCALAR_ENABLE_EXPLICIT))
#define NGS_MATH_SCALAR_USE_EXPLICIT 0
#else

#	if defined(NGS_MATH_SCALAR_DISABLE_EXPLICIT)
#		define NGS_MATH_SCALAR_USE_EXPLICIT 0
#	endif

#	if defined(NGS_MATH_SCALAR_ENABLE_EXPLICIT)
#		define NGS_MATH_SCALAR_USE_EXPLICIT 1
#	endif

#endif

#if (NGS_MATH_SCALAR_USE_EXPLICIT)
#define NGS_MATH_SCALAR_EXPLICIT true
#else
#define NGS_MATH_SCALAR_EXPLICIT false
#endif