#pragma once

#include "./placeholder.h"
#include "./defined.h"

NGS_LIB_MODULE_BEGIN
namespace placeholders
{
	template<size_t _Index>
	NGS_MODULE_EXPORT inline constexpr placeholder<_Index> n{};

#define NGS_FUNCTIONAL_PLACEHOLDERS_N(n_)				\
NGS_MODULE_EXPORT using __##n_ = placeholder<n_>;		\
NGS_MODULE_EXPORT inline constexpr auto _##n_ = n<n_>	\
//

	NGS_FUNCTIONAL_PLACEHOLDERS_N(1);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(2);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(3);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(4);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(5);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(6);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(7);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(8);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(9);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(10);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(11);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(12);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(13);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(14);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(15);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(16);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(17);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(18);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(19);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(20);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(21);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(22);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(23);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(24);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(25);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(26);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(27);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(28);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(29);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(30);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(31);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(32);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(33);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(34);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(35);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(36);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(37);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(38);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(39);
	NGS_FUNCTIONAL_PLACEHOLDERS_N(40);

#undef NGS_FUNCTIONAL_PLACEHOLDERS_N
}
NGS_LIB_MODULE_END