#pragma once

#include "../defined.h"

#define NGS_MATH_LA_VECTOR_INTERFACE_BEGIN NGS_MATH_LA_INTERFACE_BEGIN namespace vectors {
#define NGS_MATH_LA_VECTOR_INTERFACE_END } NGS_MATH_LA_INTERFACE_END
#define NGS_MATH_LA_VECTOR_ADAPTER_BEGIN NGS_MATH_LA_ADAPTER_BEGIN namespace vectors {
#define NGS_MATH_LA_VECTOR_ADAPTER_END } NGS_MATH_LA_ADAPTER_END
#define NGS_MATH_LA_VECTOR_TRAIT_BEGIN NGS_MATH_LA_TRAIT_BEGIN namespace vectors {
#define NGS_MATH_LA_VECTOR_TRAIT_END } NGS_MATH_LA_TRAIT_END