#pragma once

#define NGS_SPACE_CHIRALITY_RIGHT_HAND 1
#define NGS_SPACE_CHIRALITY_LEFT_HAND 2

#ifndef NGS_SPACE_STANDARD_CHIRALITY
#define NGS_SPACE_STANDARD_CHIRALITY NGS_SPACE_CHIRALITY_LEFT_HAND
#endif
